cargo-bins/cargo-quickinstall

.github/workflows/build-package.yml.template
.github/workflows/selfbuild.yml
Cargo.lock
build-version.sh
cargo-quickinstall/Cargo.toml
cargo-quickinstall/src/main.rs
trigger-package-build.sh

Build packages for Windows

---

popular-crates.txt
rebuild-popular-crates.sh

Improve script based on comments in #15

Improve rebuild popular crates script

---

cargo-quickinstall/src/main.rs

Refactor to use CrateDetails

---

.github/workflows/test.yml
cargo-quickinstall/src/args.rs
cargo-quickinstall/src/main.rs

Tests for the recently added command line argument processing module.
#28

Test for cli arg processing

---

.github/workflows/selfbuild.yml
build-version.sh

fixes #90 once tests pass (I'm doing this test-driven to make it harder to accidentally break it in the future)

fix running build-version.sh without ALWAYS_BUILD=1

---

Cargo.lock
cargo-quickinstall/Cargo.toml

Re enable/pico args/eq separator

---

.github/dependabot.yml

Enable dependabot for `/Cargo.lock`

---

build-version.sh

Force static linking for openssl

---

.editorconfig
.github/workflows/selfbuild.yml
.github/workflows/test.yml
build-version.sh
check-packages.sh
get-stats.sh
next-unbuilt-package.sh
rebuild-popular-crates.sh
trigger-package-build.sh

I have split this out as a separate PR because it's super-noisy. It's almost entirely indentation changes though, because at some point my vscode decided that one of the files should be indented with 2 spaces and I didn't notice.

use shfmt, and enforce in CI

---

cargo-quickinstall/src/main.rs

Call `execve` cargo-binstall on unix instead of fork + exec

---

cargo-quickinstall/src/lib.rs
cargo-quickinstall/src/main.rs

- Refactor: Extract new fn `prepare_curl_head_cmd`
- Optimize `report_stats_in_background`: Avoid `thread::spawn`
- Optimize `report_stats_in_background`: Rm one `String` creation

Optimize `report_stats_in_background`

---

cargo-quickinstall/src/lib.rs

Fix `report_stats_in_background`: Set stdin/out/err to null

---

cargo-quickinstall/src/main.rs

Avoid re-installing cargo-binstall when it is already installed

---

cargo-quickinstall/src/main.rs

Improve `do_main_binstall` dry-run output

---

.github/workflows/test.yml
cargo-quickinstall/src/args.rs
cargo-quickinstall/src/main.rs

Add support for batch installation mode

---

cargo-quickinstall/src/main.rs

Re enable boostrapping cargo-binstall on windows

---

.github/workflows/test.yml
cargo-quickinstall/src/args.rs
cargo-quickinstall/src/main.rs

Add new cmdline flag `--force`

---

cargo-quickinstall/src/main.rs

Fix `--no-fallback` when using `cargo-binstall`

---

cargo-quickinstall/src/lib.rs
cargo-quickinstall/src/main.rs
cargo-quickinstall/tests/integration_tests.rs

Fix `--dry-run` output for with/out `cargo-binstall`

---

Cargo.lock
cargo-quickinstall/Cargo.toml
cargo-quickinstall/src/lib.rs
cargo-quickinstall/src/utils.rs

Fix output of `install_crate_curl`: Print the correct `bin_dir`

---

build-version.sh

Fix `build-version.sh` for building `cargo-auditable`

---

cargo-quickinstall/src/lib.rs
cargo-quickinstall/tests/integration_tests.rs

Include `cargo-quickinstall` version in curl user-agent

---

.github/workflows/build-package.yml.template
.github/workflows/test.yml
build-version.sh
create_and_upload_tag.sh

New release/tag format: $CRATE-$VERSION

---

next-unbuilt-package.sh

Update `next-unbuilt-package.sh` to new release schema

---

cargo-quickinstall/src/lib.rs

Add support of new release schema to `cargo-quickinstall`

---

dedup-and-exclude.py
get-stats.sh
next-unbuilt-package.sh

Refactor computation of `POPULAR_CRATES` in `next-unbuilt-package.sh`

---

trigger-package-build.sh

Fix creating new branches in `trigger-package-build.sh`

---

.github/workflows/selfbuild.yml

Speedup selfbuild: Create new job self-build-with-build-version

---

build-version.sh

Check for empty `BINARIES` in `build-version.sh`

---

.github/workflows/selfbuild.yml
build-version.sh
supported-targets
trigger-package-build.sh

- aarch64-pc-windows-msvc
- aarch64-unknown-linux-musl
- armv7-unknown-linux-musleabihf
- armv7-unknown-linux-gnueabihf

Enable more targets in quickinstall

---

.github/workflows/selfbuild.yml
cargo-quickinstall/tests/integration_tests.rs
next-unbuilt-package.sh

Use `max_stable_version` from crates.io

---

.github/workflows/build-package.yml

Add new input `features` to `build-package.yml` which is set to empty by default

---

Cargo.lock
cargo-quickinstall/Cargo.toml
cargo-quickinstall/src/lib.rs
cargo-quickinstall/src/utils.rs

Fix integration test: Rm caching using `OnceBox`

---

.github/workflows/test.yml

- Provide `cargo-binstall` with `GH_TOKEN` to speedup resolution
- Enable "Test batch installation with binstall with force" for windows

Speedup test

---

.github/workflows/cronjob.yml

Increase `CRATE_CHECK_LIMIT` to 10 in cronjob

---

build-version.sh

Fallback to no `--locked` if build failed in `build-version.sh`

---

build-version.sh

Rm `echo` in `build_and_install`

Fix fallback to not `--locked` in `build-version.sh`

---

cargo-quickinstall/Cargo.toml

Release cargo-quickinstall v0.2.9

---

build-version.sh

To make sure that linking with llvm succeeds.

Export new var `LLVM_CONFIG_PATH` & `LLVM_DIR` on Linux & MacOS

---

next-unbuilt-package.sh

Enable feature `dist-server` of sccache

---

.github/workflows/build-package.yml
build-version.sh

Stop uploading in old release schema

---

build-version.sh

Add new env var `LIBCLANG_PATH` to `build-version.sh`

---

Cargo.lock

deps: Update transitive dependencies

---

next-unbuilt-package.sh

Since dist-server might pulls in openssl
Should fix #235

Fix sccache building: enable vendored-openssl & disable dist-server

---

build-version.sh
trigger-package-build.sh

macos-latest is now an alias of macos-14

Use macos-latest in trigger-package-build.sh

---

.github/workflows/test.yml

- Pass `--no-deps` to `cargo-clippy`
- pass `GITHUB_TOKEN` to any cargo-binstall invoke

Speedup test.yml

---

.github/workflows/selfbuild.yml

Speedup selfbuild.yml

---

zigbuild-requirements.txt

Use latest zig-cc compiler

---

.github/workflows/release-plz.yml

see https://github.com/cargo-bins/cargo-quickinstall/actions/runs/11793818866/job/32850152585#step:6:93

recheck needs github token

---

.github/workflows/build-package.yml
.github/workflows/cronjob.yml
.github/workflows/selfbuild.yml
cronjob_scripts/architectures.py

ci: use ubuntu-latest instead of ubuntu-20.04

---

.github/workflows/selfbuild.yml
.github/workflows/test.yml

Make it easier for branch protection setup to require ci to success for merging.

ci: Add dummy job to PR pipeline

---

.github/workflows/build-package.yml

chore(CI): customize build workflow's run-name

---

.github/workflows/deploy-stats-server.yml

Avoid triggering unnecessary deployment

ci: Only run deploy-stats-server.yml if stars-server dir changes

---

cargo-quickinstall/tests/integration_tests.rs

so that it works on release PR

Fix test_get_latest_version

---

cargo-quickinstall/tests/integration_tests.rs

Fix `test_get_latest_version` for release PR
