cargo-bins/cargo-quickinstall

cargo-quickinstall/src/main.rs
I just pushed the following changes:
1. Replaced `match` with `.map_err()` when parsing the JSON. [line 46]
2. Replaced the `.stringify()` method with `.try_into()` as you suggested, it worked. [line 47]
3. Ran `rustfmt`.
=> Replaced match with .map_err() and stringify() with try_into().

cargo-quickinstall/src/main.rs
Bintray is now returning 403 forbidden rather than 404 not found. This breaks the fallback to `cargo install`.
=> delete fallback to bintray

cargo-quickinstall/src/args.rs, cargo-quickinstall/src/main.rs
This flag causes quickinstall to abort when a pre-built package is unavailable.
Closes #41
=> Adding the --no-fallback flag.

cargo-quickinstall/src/args.rs, cargo-quickinstall/src/main.rs
These two flags are equivalent.  They print quickinstall's own version.
Closes #20
=> Adding the --print-version and -V flags

cargo-quickinstall/src/args.rs, cargo-quickinstall/src/main.rs
The ```--dry-run``` flag prints just the "curl | tar" command run during the happy path scenario where a pre-built crate binary is already available.
Closes #64
=> The --dry-run flag

LICENSE-APACHE, LICENSE-MIT, README.md
Closes #76 
This adds the license files listed in `cargo-quickinstall/Cargo.toml` to the repo along with a short notice indicating this at the bottom of the README.
I used 2020 as the starting copyright date since that's how far back the original commit adding the licenses to the `Cargo.toml` dates back (d2b05ea0442265e23f7aaab079a46d680a97229f). I also used the generic `cargo-quickinstall developers` since that seems to be a common convention instead of individually listing every contributor
=> Add license files for MIT and Apache 2.0

build-version.sh
This would be an "easy" addition to optimize some binaries.
By default `codegen-units` is set to `16`, this could do it just all at once over everthing.
Additional binary opt flags:
- `strip` affects what symbols are found in the binary
- `lto` for link time optimizations (didn't get it working)
Quickly tested it on 2 crates you seem to build, I explicitly chose 2 smaller crates as they should show to effect in even small cases. the following byte measures are from `stat --printf="%s" xyz`
- `cargo-all-features` (specificall `cargo-build-all-features`)
- No flags # 4'041'456 bytes
- `-C codegen-units=1` # 3'982'752 bytes
- `-C codegen-units=1 -C strip="symbols"` # 497'984 bytes
- `minifier` (one you've just added)
- No flags # 362'816 bytes
- `-C codegen-units=1` # 362'816 bytes
- `-C …
=> feat(build): binary opt using codegen-units

build-version.sh
The followup on #80 
That LTO thing had me bugging during lunch. And I totally forgot about the env flags cargo reads https://doc.rust-lang.org/cargo/reference/environment-variables.html
This unifies the syntax for flags used, enables lto and makes sure what ever `cargo` changes, it does not affect what `RUSTFLAGS` are provided as it is totally handled by `cargo`
=> fix(build-opt): use CARGO_PROFILE_ env vars for build opt

.github/workflows/build-package.yml.template
I think that this solves https://github.com/alsuren/cargo-quickinstall/issues/49 without any added complexity. 
I stumbled across this setting when trying to set up the webhook based scheme described in #49.
The paper trail went something like: https://github.com/organizations/cargo-quick/settings/actions
https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
This allowed me to know that it was possible at the top level, and then I jumped into vscode to see whether it was possible to use it at the job level (using the red hat yaml plugin, which pointed me at https://json.schemastore.org/github-workflow.json)
Turns out it is: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob …
=> revoke permissions for builder

.github/workflows/selfbuild.yml, build-version.sh
See https://github.com/alsuren/cargo-quickinstall/issues/87 for discussion.
=> tar defaults to format=gnu, whose sparse extension breaks the tar crate

.github/workflows/build-package.yml.template, README.md, build-version.sh, cargo-quickinstall/Cargo.toml, cargo-quickinstall/src/lib.rs, cargo-quickinstall/tests/integration_tests.rs, check-packages.sh, next-unbuilt-package.sh
Since github automatically does http redirects to the new org, there's very little left to do on #58 .
Once this is merged, we should probably make a release https://github.com/cargo-bins/cargo-quickinstall#releasing but there's no urgency - everything seems to be trucking along as usual. The only thing that broke with the rename was that `--dry-run` thinks that we have a package for everything.
I can do the release + announcement if you want, to announce the handover.
I think the only thing that's left after this is rotating secrets.CRONJOB_DEPLOY_KEY
=> update to point at cargo-bins org

.github/workflows/build-package.yml.template, .github/workflows/cronjob.yml, .github/workflows/selfbuild.yml, .github/workflows/test.yml, build-version.sh, cargo-quickinstall/src/lib.rs, check-packages.sh, next-unbuilt-package.sh, rebuild-popular-crates.sh, trigger-package-build.sh
I thought I might as well clean some long-serving uglinesses up before I hand them over. Hopefully the code review process will act as a way for @NobodyXu to learn how things work ;-)
This vaguely relates to #26 I guess.
Probably best to review things commit-by-commit. I didn't write them in that order, but the commits should be self-contained after my rebasing.
pushing to the actions branch (with a PR open against it) now triggers the following cascade (oldest at the bottom):
(you can ignore the `Automated Tests` and `Self-Build` actions)
* "weekly recheck" is triggered (as a hack) 
* it runs `make recheck` which runs `trigger-package-build.sh`
* `trigger-package-build.sh` fills in .github/workflows/build-package.yml.template a bunch of times, and pushes each to the appropriate …
=> misc build Actions cleanups

cargo-quickinstall/src/args.rs, cargo-quickinstall/src/install_error.rs, cargo-quickinstall/src/lib.rs, cargo-quickinstall/src/main.rs, cargo-quickinstall/tests/integration_tests.rs
=> Use `cargo-binstall` instead of `curl | tar` by default

Cargo.toml
Supersedes #118 
This PR is able to get both the binary size reduction as well as reduction in compilation time by using `-Oz`, stripping debug info and abort on panic.
It was able to reduce size from 700K => 476K while reducing compilation time on my M1 from 1s => 0.75s.
=> Tweak release build settings to reduce size and compilation time

.github/workflows/test.yml, cargo-quickinstall/tests/integration_tests.rs
The former works more reliably, including on a shallow repository with tags fetched.
=> Fix `test_get_latest_version`: Use `git-tag` instead of `git-describe`

.github/workflows/test.yml, Cargo.lock, cargo-quickinstall/Cargo.toml, cargo-quickinstall/src/lib.rs, cargo-quickinstall/src/main.rs
* Add new dep tempfile v3.3.0
* Impl new fn `curl_file`
* Install binstall from upstream if possible
* Add e2etest for installing and using cargo-binstall
* Refactor: Extract new fn `format_curl_and_untar_cmd`
* Refactor: Extract new fn `get_quickinstall_download_url`
* Runs e2e tests on windows, macos and ubuntu
* Disable bootstraping binstall on windows
=> Download binstall from upstream if possible and add e2etest

popular-crates.txt
I'd like quickinstall to provide pre-built artifacts for `cargo-auditable` so that we can use it in cargo-binstall and cargo-quickinstall.
=> Add `cargo-auditable` to `popular-crates.txt`

Cargo.lock, cargo-quickinstall/Cargo.toml, cargo-quickinstall/src/lib.rs
=> Fallback to `guess_host_triple` if `rustc -vV` failed

.github/workflows/build-package.yml.template, .github/workflows/selfbuild.yml, build-version.sh
Fixed #133
so that it contains version information that can be extracted by tools such as `cargo-audit` to check for vulnerabilities.
=> Use `cargo-auditable` to build the binaries

.github/workflows/test.yml, cargo-quickinstall/src/args.rs, cargo-quickinstall/src/main.rs
This addresses all of the things I noticed in https://github.com/cargo-bins/cargo-quickinstall/issues/126
I decided to disable versioned symlinks because I find them annoying (they break my tab completion) and they're not something that `cargo install` does natively.
I decided to make searching for upstream packages opt-in because they're slow. Disabling that strategy brings the time for `cargo quickinstall bat --force` down from 10 seconds to 2 seconds. Still not as good as `cargo quickinstall bat --force --no-binstall` (1 second), but good enough for me. I also quite like the simplicity of the explanation "`cargo quickinstall $package` will always give you something equivalent to `cargo install $package`". I have allowed users to opt-in with the `--try-upstream` flag. There might be a …
=> Fixes for my release feedback notes

next-unbuilt-package.sh
I was looking at aarch64 build failures and found https://github.com/cargo-bins/cargo-quickinstall/actions/runs/4037215661/jobs/6940354885#step:5:87
```
error: cannot install package `cargo-chef`, it has been yanked from registry `crates-io`
```
=> latest crate version might be yanked

cargo-quickinstall/src/main.rs
=> Fix installing `cargo-binstall` in `do_main_binstall`

cargo-quickinstall/src/lib.rs
htttps://crates.io/api/v1/crates/$name contains a field `.crate|.max_stable_version`, which is the stable version listed on https://crates.io/crates/$name
https://rust-lang.zulipchat.com/#narrow/stream/318791-t-crates-io/topic/.E2.9C.94.20How.20to.20get.20the.20latest.20version.20from.20crates.2Eio.3F
=> Optimize `get_latest_version`: Use field `.crate|.max_stable_version`

README.md, supported-targets, trigger-package-build.sh
which lists all targets quickinstall can build for.
I intend to also use this in cargo-binstall to reduce amount of http requests sent to GitHub.
=> Add `supported-targets`

get-stats.sh
> parse error: Invalid numeric literal at line 1, column 10
-- https://github.com/cargo-bins/cargo-quickinstall/actions/runs/4337401745/jobs/7573375129#step:3:78
The underlying error is `[ioredis] Unhandled error event: ReplyError: ERR max daily request limit exceeded. Limit: 10000, Usage: 10000. See https://docs.upstash.com/overall/databasetypes for details` but that's in the server logs at https://vercel.com/alsuren/warehouse-clerk-tmp/logs?page=3&timeline=past30Minutes&startDate=1678040918696&endDate=1678042718696&selectedLogId=1678041917367918720482439920&selectedLogTimestamp=1678041917367&forceEndDate=1678042132566 and I don't have a way to share that.
Hopefully when we rip out the vercel+redis stats server we can stop having this problem.
=> make cronjob still work when stats server is down

build-version.sh
Fixed #170
Also fix build on aarch64-unknown-linux-gnu: Build crate with `cargo-auditable`.
=> Build crates with `--locked`

build-version.sh
=> Fix bootstrapping `cargo-auditable` in x86_64-unknown-linux-musl

build-version.sh
so that more crates depended on present of `libllvm` or `llvm-config` can be built.
=> Install llvm in `build-version.sh`

build-version.sh
Homebrew is just way too slow and `brew install llvm` also installs its own `glibc` and the `libllvm` seems to use latest glibc symbols that are missing on ubuntu-20.04.
=> Use `apt` to install llvm on linux

next-unbuilt-package.sh
Fix bug in `next-unbuilt-package.sh`: Ensure every crate in `POPULAR_CRATES` already has their crates.io response downloaded.
This would also avoid creating new build for `cargo-quickinstall` when it is already built and uploaded.
=> Fix cronjob/weekly-build failure

.github/workflows/test.yml, Cargo.lock
since cargo-nextest 0.9.26 isn't available in the new quickinstall release schema BUT cargo-binstall v0.21.x only supports quickinstall new release schema.
=> Fix e2etest: Install cargo-nextest v0.9.50 instead of 0.9.28

.github/workflows/build-package.yml, .gitignore, build-version.sh, next-unbuilt-package.sh
`gitoxide` is crate intended to be an alternative of `git`.
It currently fails on cross compilation due to lack of system-wide openssl installation.
It's quite popular, so I think we should fix building `gitoxide` in quickinstall.
According to @Byron in https://github.com/Byron/gitoxide/issues/809 , we can fix the by building gitoxide with `--no-default-features --featulres max-pure`.
- Add new input `no_default_features` to `build-package.yml`
- Build gitoxide with `--no-default-features --features max-pure`
- Add `\.DS_Store` to `.gitignore`
=> Fix building gitoxide

popular-crates.txt
I'm proposing to add two more crates which are useful in CI context:
1. [`cargo-nextest`](https://github.com/nextest-rs/nextest) is a modern [test runner](https://nexte.st/) which is capable to provide `junit.xml` suitable for ingeration with other tools like GitLab;
2. [`cargo-llvm-cov`](https://github.com/taiki-e/cargo-llvm-cov) is yet another code coverage tool gaining popularity;
=> Added nextest & llvm-cov crates.

.github/workflows/selfbuild.yml, build-version.sh, zigbuild-requirements.txt
- Fixed `build-version.sh`: Remove duplicate `--locked`
- Fixed `selfbuild.yml` job `build-needing-cc`: Remove outdated non-existent `FEATURES` for `cargo-deny`
=> Fix CI: Fix package build & self testing

build-version.sh
To maintain backwards compatibility with older distro
=> Build using glibc 2.17

.github/workflows/build-package.yml, .github/workflows/selfbuild.yml, build-version.sh
Since it can be trivially overwritten by malicious actor, it doesn't have much use'
=> Remove cargo-auditable

cargo-quickinstall/tests/integration_tests.rs
It would be temporarily broken during release, but this is the most robust
=> Fix test_get_latest_version

cargo-quickinstall/src/install_error.rs, cargo-quickinstall/src/lib.rs, cargo-quickinstall/src/main.rs, stats-server/src/main.rs
This requires us to move the reporting to happen after we've done the install, but let's not quibble about a few milliseconds here or there, when we may have saved the user multiple minutes.
Also drop unknown query params in server now that we have a good idea of  which stats we want to collect. If anyone wants to track anything else, it should be easy enough to add them here as a pull request.
Feel free to rip into my rust. It is about as rusty as my python ;-).
=> report stats to new server, with status

Makefile, cronjob_scripts/architectures.py, cronjob_scripts/trigger-package-build.py
python 3.8 doesn't understand `list[str]` as a type annotation at runtime (see error in https://github.com/cargo-bins/cargo-quickinstall/issues/282).
This wasn't caught because I was accidentally smoke-testing locally on a more modern python.
I was also pushing to the actions branch to test on CI, but forgot to do that between making a last minute refactor and merging to main.
I think this test will avoid similar problems with shipping broken python code.
Note that we don't do any mypy type checking in CI, so it's up to whatever you have enabled in your IDE to catch any discrepancies.
=> Fix python

stats-server/src/main.rs
I just pushed https://github.com/cargo-bins/cargo-binstall/pull/1912 which points users to https://cargo-quickinstall-stats-server.fly.dev/record-install
If you go there, it previously returned a 405 "method forbidden" error.
I have changed it so that it now redirects to /.
I already made the deploy. Feel free to merge if you're happy with this.
=> redirect to / when people's browsers are directed to /record-install by cargo-binstall

cronjob_scripts/trigger-package-build.py
Motivation:
Some crates, e.g. https://docs.rs/crate/cargo-docset/latest/features , have a `bundled-*` feature to build a vendored C/C++ library, which is necessary for cross-compilation and reliable distribution.
=> Enable all feature including "bundled"

stats-server/Cargo.lock, stats-server/Cargo.toml
influxrs 2.1 has included the escape fix, so using a fork is no longer necessary.
=> Bump dep influrs for stats-server to 3.0

.github/workflows/deploy-stats-server.yml, stats-server/Cargo.lock, stats-server/Cargo.toml, stats-server/fly.toml, stats-server/src/main.rs
This reverts #303 because it is causing the following in our logs: https://fly.io/apps/cargo-quickinstall-stats-server/monitoring
```
2024-10-01T15:14:50.843 app[7811ee7a2566e8] iad [info] called `Result::unwrap()` on an `Err` value: NonSuccessResponse(400, "{\"code\":\"invalid\",\"message\":\"no data written, errors encountered on line(s): line 1: timestamp value overflows after adjusting for specified precision\",\"line\":1}")
```
I'm not in the mood to debug it right now, but I **think** that if the new docker container fails to come up, the old one should stay in the load balancer and prevent an outage (note: this is not the case with the default strategy, but it is with the bluegreen strategy). 
With the healthcheck and a bluegreen deployment strategy, we get a nonzero exit code from …
=> revert influx lib upgrade; Influx smoke test before listening on http port.

.github/workflows/test.yml, cargo-quickinstall/build.rs, stats-server/src/main.rs
I just pulled main and got:
```
warning: unused `embed_resource::CompilationResult` that must be used
--> cargo-quickinstall/build.rs:6:5
|
6 |     embed_resource::compile("manifest.rc", embed_resource::NONE);
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: `-D unused-must-use` implied by `-D warnings`
= help: to override `-D warnings` add `#[allow(unused_must_use)]`
help: use `let _ = ...` to ignore the resulting value
|
6 |     let _ = embed_resource::compile("manifest.rc", embed_resource::NONE);
|     +++++++
warning: `cargo-quickinstall` (build script) generated 1 warning
Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.96s
```
This seems like it was caused by #319 and not caught by our CI.
I also ran clippy in the stats-server project and …
=> Squash warning after embed-resource version bump; enable clippy in ci

.github/workflows/build-package.yml, .github/workflows/cronjob.yml, .github/workflows/test.yml, cargo-quickinstall/src/install_error.rs, cargo-quickinstall/tests/integration_tests.rs
The SSH Deploy key was previously used to trigger cascades of workflows by pushing to the relevant trigger branches. We don't do this anymore, but we were still using the deploy key to do the initial checkout in the cronjob workflow. I deleted it as part of my reponse to #441, and the cronjob [started failing](https://github.com/cargo-bins/cargo-quickinstall/actions/runs/17346869585) when I re-enabled it.
=> Get cronjob working again after I deleted the deploy key
